# aws cloudformation create-stack --stack-name utopiaRds--template-body file://$PWD/rds.yml 
AWSTemplateFormatVersion: "2010-09-09"
Description: "Utopia airline base infstructure"
Resources:
  UtopiaRDS:
    Type: 'AWS::RDS::DBInstance'
    Properties:
        DBName: "utopia"
        DBInstanceIdentifier: "utopiards"
        Engine: MySQL
        MasterUsername: '{{resolve:secretsmanager:UtopiaSecretManager:SecretString:username}}'
        MasterUserPassword: '{{resolve:secretsmanager:UtopiaSecretManager:SecretString:password}}'
        DBInstanceClass: db.t2.micro
        AllocatedStorage: '5'
        PubliclyAccessible: true
        VPCSecurityGroups:
            - !Ref RDSSecurityGroup

  RDSSecurityGroup:
      Type: "AWS::EC2::SecurityGroup"
      Properties:
          GroupDescription: "Allows MySQL"
          GroupName: "utopiaMySQL"
          VpcId: "vpc-0d17b977"
          SecurityGroupIngress: 
            - 
              CidrIp: "0.0.0.0/0"
              FromPort: 3306
              IpProtocol: "tcp"
              ToPort: 3306
            - 
              CidrIpv6: "::/0"
              FromPort: 3306
              IpProtocol: "tcp"
              ToPort: 3306
          SecurityGroupEgress: 
            - 
              CidrIp: "0.0.0.0/0"
              IpProtocol: "-1"

Outputs:
  RDS:
    Value: !Ref UtopiaRDS
    Export:
      Name: UtopiaRDS
  RDSEndpoint:
    Value: !GetAtt UtopiaRDS.Endpoint.Address
    Export:
      Name: RDSEndpoint